name: Seq2UMTree
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - dataclasses-json
  - ipykernel
  - numpy
  - pytorch=*=*cuda*
  - spacy
  - spacy-model-en_core_web_sm
  - tqdm
  - xmltodict
