name: OpenJERE
channels:
  - cerebis
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - matplotlib-base
  - numpy
  - overrides
  - pytorch=*=*cuda*
  - spacy
  - spacy-model-en_core_web_sm
  - tqdm
  - transformers
  - xmltodict
